version: "3.4"

services:
  pwa: &pwa
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:${APP_BUILD}
    build: pwa
    ports:
      - "81:8080"
volumes:
  db-data: {}
  uc-data: {}
  db-mysql: {}