name: My Open Catalogi Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@latest
        with:
          opencatalogi: true
      - name: Create an Open Catalogi page
        uses: OpenCatalogi/opencatalogi-action@1.0.0
        with:
          github_repository_name_as_prefix: false
          nl_design_theme_classname: 'rotterdam-theme'
          pull_from_branche: 'development'
          start_page: 'https://github.com/OpenCatalogi/.github/blob/main/docs/Catalogi.md'
          favicon_logo: 'https://www.rotterdam.nl/images/logo-base.svg'
          navbar_logo: 'https://www.rotterdam.nl/images/logo-base.svg'
          footer_logo: 'https://www.rotterdam.nl/images/logo-base.svg'
