name: My PublicCode Workflow

permissions:
  contents: write

on:
  push:
    branches:
      - never

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@latest
